import React, { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, ChevronDown, Loader2, CheckCircle2 } from 'lucide-react';
import { orphanTasksApi, OrphanTask, departmentsApi, tasksApi } from '../../services/api';
import { useToast } from '../../hooks/useToast';
import UserAvatar from '../ui/UserAvatar';

/**
 * Admin triage page.
 * Lists every active task that has no assigned_post_id — these are "orphan" tasks
 * that don't show up under any post in the org chart. Usually legacy tasks from
 * before the post-required validation, or recurring instances generated by the
 * old recurring flow.
 *
 * For each task, the admin picks a department → subdepartment → post from the
 * three inline selects, and hits "Atribuie". The task gets assigned_post_id set
 * and (if the post has a user) assigned_to is updated by the backend too.
 */
export default function OrphanTasksPage() {
    const { showToast } = useToast();
    const [tasks, setTasks] = useState<OrphanTask[]>([]);
    const [loading, setLoading] = useState(true);
    const [orgDepts, setOrgDepts] = useState<any[]>([]);

    // Per-task local selections: { [taskId]: { deptId, sectionId, postId } }
    const [selection, setSelection] = useState<Record<string, { deptId: string; sectionId: string; postId: string }>>({});
    const [saving, setSaving] = useState<Record<string, boolean>>({});

    async function loadAll() {
        setLoading(true);
        try {
            const [o, d] = await Promise.all([
                orphanTasksApi.list(),
                departmentsApi.list(),
            ]);
            setTasks(o.tasks);
            setOrgDepts(d.departments || []);
        } catch {
            showToast('Eroare la încărcare', 'error');
        } finally {
            setLoading(false);
        }
    }

    useEffect(() => { loadAll(); }, []);

    function updateSelection(taskId: string, field: 'deptId' | 'sectionId' | 'postId', value: string) {
        setSelection(prev => {
            const cur = prev[taskId] || { deptId: '', sectionId: '', postId: '' };
            const next = { ...cur, [field]: value };
            // Cascading reset: changing dept clears section+post; changing section clears post.
            if (field === 'deptId') { next.sectionId = ''; next.postId = ''; }
            if (field === 'sectionId') next.postId = '';
            return { ...prev, [taskId]: next };
        });
    }

    async function assignPost(taskId: string) {
        const sel = selection[taskId];
        if (!sel?.postId) {
            showToast('Alege postul', 'error');
            return;
        }
        setSaving(prev => ({ ...prev, [taskId]: true }));
        try {
            // Backend auto-resolves assigned_to from post.user_id when assigned_to is undefined
            await tasksApi.update(taskId, { assigned_post_id: sel.postId } as any);
            showToast('Post atribuit!');
            // Remove the task from the list
            setTasks(prev => prev.filter(t => t.id !== taskId));
        } catch {
            showToast('Nu a funcționat — încearcă din nou', 'error');
        } finally {
            setSaving(prev => ({ ...prev, [taskId]: false }));
        }
    }

    function postForTask(taskId: string) {
        const sel = selection[taskId];
        if (!sel) return null;
        const dept = orgDepts.find(d => d.id === sel.deptId);
        const section = dept?.sections?.find((s: any) => s.id === sel.sectionId);
        const post = section?.posts?.find((p: any) => p.id === sel.postId);
        return { dept, section, post };
    }

    return (
        <div className="p-4 md:p-6 max-w-[1200px] mx-auto w-full animate-fade-in">
            <div className="mb-5 flex items-start justify-between flex-wrap gap-2">
                <div>
                    <h1 className="text-2xl font-bold flex items-center gap-2">
                        <AlertTriangle className="w-6 h-6 text-amber-400" />
                        Sarcini orfane
                    </h1>
                    <p className="text-navy-400 text-sm mt-1">
                        Sarcini fără post asignat — nu apar sub nicio unitate în organigramă.
                        Atribuie-le un post ca să devină vizibile pentru întreaga echipă.
                    </p>
                </div>
                <button
                    onClick={loadAll}
                    className="flex items-center gap-1.5 px-3 py-2 bg-navy-800/50 border border-navy-700/50 rounded-lg text-xs hover:bg-navy-700/50"
                >
                    <RefreshCw className="w-3.5 h-3.5" /> Reîncarcă
                </button>
            </div>

            {loading ? (
                <div className="flex items-center justify-center py-16 text-navy-400">
                    <Loader2 className="w-5 h-5 animate-spin mr-2" /> Se încarcă…
                </div>
            ) : tasks.length === 0 ? (
                <div className="text-center py-16">
                    <CheckCircle2 className="w-12 h-12 text-green-400/60 mx-auto mb-3" />
                    <p className="text-navy-300 text-sm font-medium">Toate sarcinile au post asignat!</p>
                    <p className="text-navy-500 text-xs mt-1">Nu sunt sarcini orfane de rezolvat.</p>
                </div>
            ) : (
                <>
                    <p className="text-xs text-navy-400 mb-3">
                        {tasks.length} {tasks.length === 1 ? 'sarcină' : 'sarcini'} fără post.
                        Cele marcate cu 🔁 sunt șabloane recurente — atribuind postul, toate instanțele viitoare vor moșteni automat.
                    </p>
                    <div className="space-y-2">
                        {tasks.map(task => {
                            const sel = selection[task.id] || { deptId: '', sectionId: '', postId: '' };
                            const dept = orgDepts.find(d => d.id === sel.deptId);
                            const sections = dept?.sections || [];
                            const section = sections.find((s: any) => s.id === sel.sectionId);
                            const posts = section?.posts || [];
                            const chosen = postForTask(task.id);

                            return (
                                <div key={task.id} className="bg-navy-900/50 border border-navy-700/50 rounded-xl p-3">
                                    {/* Top row: title + creator/assignee */}
                                    <div className="flex items-start gap-3 mb-2">
                                        <div className="flex-1 min-w-0">
                                            <div className="flex items-center gap-2 flex-wrap">
                                                {task.is_recurring_template && (
                                                    <span
                                                        className="text-[10px] px-1.5 py-0.5 rounded bg-cyan-500/20 text-cyan-300 border border-cyan-500/30"
                                                        title="Șablon recurent — instanțele viitoare vor moșteni postul"
                                                    >
                                                        🔁 recurent
                                                    </span>
                                                )}
                                                <h3 className="text-sm font-semibold text-white truncate">{task.title}</h3>
                                            </div>
                                            <div className="flex items-center gap-3 mt-1 text-[10px] text-navy-500">
                                                <span className="flex items-center gap-1">
                                                    <UserAvatar name={task.creator_name} avatarUrl={task.creator_avatar} size="xs" />
                                                    creat de {task.creator_name}
                                                </span>
                                                {task.assignee_name && (
                                                    <span className="flex items-center gap-1">
                                                        <UserAvatar name={task.assignee_name} avatarUrl={task.assignee_avatar} size="xs" />
                                                        → {task.assignee_name}
                                                    </span>
                                                )}
                                                <span>scadent {task.due_date}</span>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Three selects + action */}
                                    <div className="flex flex-col md:flex-row gap-2 items-stretch md:items-end">
                                        <div className="flex-1">
                                            <label className="block text-[10px] text-navy-500 mb-0.5">Departament *</label>
                                            <select
                                                value={sel.deptId}
                                                onChange={(e) => updateSelection(task.id, 'deptId', e.target.value)}
                                                className="w-full px-2 py-1.5 bg-navy-800/50 border border-navy-700/50 rounded text-xs text-white focus:outline-none focus:border-blue-500/50"
                                            >
                                                <option value="">— alege —</option>
                                                {orgDepts.map(d => (
                                                    <option key={d.id} value={d.id}>{d.name}</option>
                                                ))}
                                            </select>
                                        </div>
                                        <div className="flex-1">
                                            <label className="block text-[10px] text-navy-500 mb-0.5">Subdepartament *</label>
                                            <select
                                                value={sel.sectionId}
                                                onChange={(e) => updateSelection(task.id, 'sectionId', e.target.value)}
                                                disabled={!sel.deptId}
                                                className="w-full px-2 py-1.5 bg-navy-800/50 border border-navy-700/50 rounded text-xs text-white focus:outline-none focus:border-blue-500/50 disabled:opacity-40"
                                            >
                                                <option value="">— alege —</option>
                                                {sections.map((s: any) => (
                                                    <option key={s.id} value={s.id}>{s.name}</option>
                                                ))}
                                            </select>
                                        </div>
                                        <div className="flex-1">
                                            <label className="block text-[10px] text-navy-500 mb-0.5">Post *</label>
                                            <select
                                                value={sel.postId}
                                                onChange={(e) => updateSelection(task.id, 'postId', e.target.value)}
                                                disabled={!sel.sectionId}
                                                className="w-full px-2 py-1.5 bg-navy-800/50 border border-navy-700/50 rounded text-xs text-white focus:outline-none focus:border-blue-500/50 disabled:opacity-40"
                                            >
                                                <option value="">— alege —</option>
                                                {posts.map((p: any) => (
                                                    <option key={p.id} value={p.id}>
                                                        {p.name}{p.user_name ? ` → ${p.user_name}` : ' (neocupat)'}
                                                    </option>
                                                ))}
                                            </select>
                                        </div>
                                        <button
                                            onClick={() => assignPost(task.id)}
                                            disabled={!sel.postId || saving[task.id]}
                                            className="px-4 py-2 bg-blue-500 hover:bg-blue-400 text-white rounded text-xs font-medium disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                                        >
                                            {saving[task.id] ? 'Se salvează…' : 'Atribuie'}
                                        </button>
                                    </div>
                                    {chosen?.post?.user_name && sel.postId && (
                                        <p className="text-[10px] text-navy-400 mt-1.5">
                                            Responsabil: <span className="text-blue-400">{chosen.post.user_name}</span>
                                        </p>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </>
            )}
        </div>
    );
}
